### ISSUE TITLE
Plugin fatal errors when no connection

### ISSUE THREAD

**Issue by jtsternberg** [WebDevStudios/WP-Contributions#18]
Using locally and when the wifi is disabled, I get a string of errors followed by a fatal error:

^[[1;2B[21-May-2015 02:41:15 UTC] PHP Warning:  Illegal string offset 'query' in /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php on line 58
[21-May-2015 02:41:15 UTC] PHP Stack trace:
[21-May-2015 02:41:15 UTC] PHP   1. {main}() /index.php:0
[21-May-2015 02:41:15 UTC] PHP   2. require() /index.php:17
[21-May-2015 02:41:15 UTC] PHP   3. require_once() /wp-blog-header.php:16
[21-May-2015 02:41:15 UTC] PHP   4. include() /wp-includes/template-loader.php:74
[21-May-2015 02:41:15 UTC] PHP   5. get_sidebar() /wp-content/themes/organic_swell/index.php:82
[21-May-2015 02:41:15 UTC] PHP   6. locate_template() /wp-includes/general-template.php:125
[21-May-2015 02:41:15 UTC] PHP   7. load_template() /wp-includes/template.php:477
[21-May-2015 02:41:15 UTC] PHP   8. require_once() /wp-includes/template.php:501
[21-May-2015 02:41:15 UTC] PHP   9. dynamic_sidebar() /wp-content/themes/organic_swell/sidebar-left.php:15
[21-May-2015 02:41:15 UTC] PHP  10. call_user_func_array() /wp-includes/widgets.php:1272
[21-May-2015 02:41:15 UTC] PHP  11. WP_Widget->display_callback() /wp-includes/widgets.php:1272
[21-May-2015 02:41:15 UTC] PHP  12. WDS_WP_Contributions_Codex_Widget->widget() /wp-includes/widgets.php:329
[21-May-2015 02:41:15 UTC] PHP  13. WDS_WP_Contributions->display_card() /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex-widget.php:118
[21-May-2015 02:41:15 UTC] PHP  14. WDS_WP_Contributions_Codex->display() /wp-content/plugins/wp-contributions/wp-contributions.php:166
[21-May-2015 02:41:15 UTC] PHP  15. WDS_WP_Contributions_Codex::get_codex_items() /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php:123
[21-May-2015 02:41:15 UTC] PHP Notice:  Uninitialized string offset: 0 in /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php on line 58
[21-May-2015 02:41:15 UTC] PHP Stack trace:
[21-May-2015 02:41:15 UTC] PHP   1. {main}() /index.php:0
[21-May-2015 02:41:15 UTC] PHP   2. require() /index.php:17
[21-May-2015 02:41:15 UTC] PHP   3. require_once() /wp-blog-header.php:16
[21-May-2015 02:41:15 UTC] PHP   4. include() /wp-includes/template-loader.php:74
[21-May-2015 02:41:15 UTC] PHP   5. get_sidebar() /wp-content/themes/organic_swell/index.php:82
[21-May-2015 02:41:15 UTC] PHP   6. locate_template() /wp-includes/general-template.php:125
[21-May-2015 02:41:15 UTC] PHP   7. load_template() /wp-includes/template.php:477
[21-May-2015 02:41:15 UTC] PHP   8. require_once() /wp-includes/template.php:501
[21-May-2015 02:41:15 UTC] PHP   9. dynamic_sidebar() /wp-content/themes/organic_swell/sidebar-left.php:15
[21-May-2015 02:41:15 UTC] PHP  10. call_user_func_array() /wp-includes/widgets.php:1272
[21-May-2015 02:41:15 UTC] PHP  11. WP_Widget->display_callback() /wp-includes/widgets.php:1272
[21-May-2015 02:41:15 UTC] PHP  12. WDS_WP_Contributions_Codex_Widget->widget() /wp-includes/widgets.php:329
[21-May-2015 02:41:15 UTC] PHP  13. WDS_WP_Contributions->display_card() /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex-widget.php:118
[21-May-2015 02:41:15 UTC] PHP  14. WDS_WP_Contributions_Codex->display() /wp-content/plugins/wp-contributions/wp-contributions.php:166
[21-May-2015 02:41:15 UTC] PHP  15. WDS_WP_Contributions_Codex::get_codex_items() /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php:123
[21-May-2015 02:41:15 UTC] PHP Warning:  Illegal string offset 'usercontribs' in /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php on line 58
[21-May-2015 02:41:15 UTC] PHP Stack trace:
[21-May-2015 02:41:15 UTC] PHP   1. {main}() /index.php:0
[21-May-2015 02:41:15 UTC] PHP   2. require() /index.php:17
[21-May-2015 02:41:15 UTC] PHP   3. require_once() /wp-blog-header.php:16
[21-May-2015 02:41:15 UTC] PHP   4. include() /wp-includes/template-loader.php:74
[21-May-2015 02:41:15 UTC] PHP   5. get_sidebar() /wp-content/themes/organic_swell/index.php:82
[21-May-2015 02:41:15 UTC] PHP   6. locate_template() /wp-includes/general-template.php:125
[21-May-2015 02:41:15 UTC] PHP   7. load_template() /wp-includes/template.php:477
[21-May-2015 02:41:15 UTC] PHP   8. require_once() /wp-includes/template.php:501
[21-May-2015 02:41:15 UTC] PHP   9. dynamic_sidebar() /wp-content/themes/organic_swell/sidebar-left.php:15
[21-May-2015 02:41:15 UTC] PHP  10. call_user_func_array() /wp-includes/widgets.php:1272
[21-May-2015 02:41:15 UTC] PHP  11. WP_Widget->display_callback() /wp-includes/widgets.php:1272
[21-May-2015 02:41:15 UTC] PHP  12. WDS_WP_Contributions_Codex_Widget->widget() /wp-includes/widgets.php:329
[21-May-2015 02:41:15 UTC] PHP  13. WDS_WP_Contributions->display_card() /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex-widget.php:118
[21-May-2015 02:41:15 UTC] PHP  14. WDS_WP_Contributions_Codex->display() /wp-content/plugins/wp-contributions/wp-contributions.php:166
[21-May-2015 02:41:15 UTC] PHP  15. WDS_WP_Contributions_Codex::get_codex_items() /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php:123
[21-May-2015 02:41:15 UTC] PHP Notice:  Uninitialized string offset: 0 in /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php on line 58
[21-May-2015 02:41:15 UTC] PHP Stack trace:
[21-May-2015 02:41:15 UTC] PHP   1. {main}() /index.php:0
[21-May-2015 02:41:15 UTC] PHP   2. require() /index.php:17
[21-May-2015 02:41:15 UTC] PHP   3. require_once() /wp-blog-header.php:16
[21-May-2015 02:41:15 UTC] PHP   4. include() /wp-includes/template-loader.php:74
[21-May-2015 02:41:15 UTC] PHP   5. get_sidebar() /wp-content/themes/organic_swell/index.php:82
[21-May-2015 02:41:15 UTC] PHP   6. locate_template() /wp-includes/general-template.php:125
[21-May-2015 02:41:15 UTC] PHP   7. load_template() /wp-includes/template.php:477
[21-May-2015 02:41:15 UTC] PHP   8. require_once() /wp-includes/template.php:501
[21-May-2015 02:41:15 UTC] PHP   9. dynamic_sidebar() /wp-content/themes/organic_swell/sidebar-left.php:15
[21-May-2015 02:41:15 UTC] PHP  10. call_user_func_array() /wp-includes/widgets.php:1272
[21-May-2015 02:41:15 UTC] PHP  11. WP_Widget->display_callback() /wp-includes/widgets.php:1272
[21-May-2015 02:41:15 UTC] PHP  12. WDS_WP_Contributions_Codex_Widget->widget() /wp-includes/widgets.php:329
[21-May-2015 02:41:15 UTC] PHP  13. WDS_WP_Contributions->display_card() /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex-widget.php:118
[21-May-2015 02:41:15 UTC] PHP  14. WDS_WP_Contributions_Codex->display() /wp-content/plugins/wp-contributions/wp-contributions.php:166
[21-May-2015 02:41:15 UTC] PHP  15. WDS_WP_Contributions_Codex::get_codex_items() /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php:123
[21-May-2015 02:41:15 UTC] PHP Warning:  Invalid argument supplied for foreach() in /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php on line 58
[21-May-2015 02:41:15 UTC] PHP Stack trace:
[21-May-2015 02:41:15 UTC] PHP   1. {main}() /index.php:0
[21-May-2015 02:41:15 UTC] PHP   2. require() /index.php:17
[21-May-2015 02:41:15 UTC] PHP   3. require_once() /wp-blog-header.php:16
[21-May-2015 02:41:15 UTC] PHP   4. include() /wp-includes/template-loader.php:74
[21-May-2015 02:41:15 UTC] PHP   5. get_sidebar() /wp-content/themes/organic_swell/index.php:82
[21-May-2015 02:41:15 UTC] PHP   6. locate_template() /wp-includes/general-template.php:125
[21-May-2015 02:41:15 UTC] PHP   7. load_template() /wp-includes/template.php:477
[21-May-2015 02:41:15 UTC] PHP   8. require_once() /wp-includes/template.php:501
[21-May-2015 02:41:15 UTC] PHP   9. dynamic_sidebar() /wp-content/themes/organic_swell/sidebar-left.php:15
[21-May-2015 02:41:15 UTC] PHP  10. call_user_func_array() /wp-includes/widgets.php:1272
[21-May-2015 02:41:15 UTC] PHP  11. WP_Widget->display_callback() /wp-includes/widgets.php:1272
[21-May-2015 02:41:15 UTC] PHP  12. WDS_WP_Contributions_Codex_Widget->widget() /wp-includes/widgets.php:329
[21-May-2015 02:41:15 UTC] PHP  13. WDS_WP_Contributions->display_card() /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex-widget.php:118
[21-May-2015 02:41:15 UTC] PHP  14. WDS_WP_Contributions_Codex->display() /wp-content/plugins/wp-contributions/wp-contributions.php:166
[21-May-2015 02:41:15 UTC] PHP  15. WDS_WP_Contributions_Codex::get_codex_items() /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php:123
[21-May-2015 02:41:15 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php:102
Stack trace:
#0 /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php(102): SimpleXMLElement->__construct('')
#1 /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php(124): WDS_WP_Contributions_Codex::get_codex_count('jtsternberg')
#2 /wp-content/plugins/wp-contributions/wp-contributions.php(166): WDS_WP_Contributions_Codex->display('jtsternberg', 5)
#3 /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex-widget.php(118): WDS_WP_Contributions->display_card(Array)
#4 /wp-includes/widgets.php(329): WDS_WP_Contributions_Codex_Widget->widget(Array, Array)
#5 [internal function]: WP_Widget->display_callback(Array, Array)
#6 in /wp-content/plugins/wp-contributions/inc/class-wds-wp-contributions-codex.php on line 102

**Comment by colorful-tones** [comment]
I'm thinking this might have something to do with the usage of `wp_get_remote()` for retrieving WP.org API info. We should be checking for error response and provide fallback message if someone doesn't have network to reach out to WP.org API?

**Comment by tw2113** [comment]
With this one, a lot of it is going to be just reading through the notices/warnings that Justin originally pasted, and do preventive measures for them.

For example " Invalid argument supplied for foreach() in /inc/class-wds-wp-contributions-codex.php on line 58" we would want to add an `is_array()` check.

As per Justin's specific notes, it sounds like we're trying to pass a string into `SimpleXMLElement()`, perhaps as a default value that didn't get changed with the existence of network connectivity. 

Instead of trying to think about this too hard, I would say a try/catch block in the area where we're trying to parse XML would be ideal, and only set the transients in that area, if we don't encounter an exception.

Alternatively, we have the option to fetch json in this area instead of xml, as this endpoint is just mediawiki https://codex.wordpress.org/api.php, in case we want to change up what and how we store the data.

**Comment by tw2113** [comment]
Fixed as part of https://github.com/WebDevStudios/WP-Contributions/pull/30
